some yaml fixes

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -7,7 +7,10 @@ mapfile -t FILES < <(git ls-files '*.yml' '*.yaml' \
 
 if ((${#FILES[@]})); then
   echo "[pre-push] yamllint"
-  .venv/bin/yamllint -s "${FILES[@]}"
+  .venv/bin/yamllint -s "${FILES[@]}" || Y=$?
+  if [[ "${Y:-0}" -eq 1 ]]; then
+    echo "[pre-push] yamllint errors"; exit 1
+  fi
 
   echo "[pre-push] ansible-lint"
   .venv/bin/ansible-lint "${FILES[@]}"
